# Generated by Django 3.2.10 on 2024-01-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo1', models.CharField(max_length=100)),
                ('equipo2', models.CharField(max_length=100)),
                ('resultado', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'ResultadoPartido',
                'verbose_name_plural': 'ResultadoPartidos',
            },
        ),
    ]
