# Generated by Django 3.2.10 on 2024-01-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llenar_quiniela', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquiposPartidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j', models.IntegerField()),
                ('eq1', models.CharField(max_length=100)),
                ('eq2', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'EquiposPartidos',
                'verbose_name_plural': 'EquiposPartidos',
            },
        ),
    ]
