# Generated by Django 3.2.10 on 2024-01-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llenar_quiniela', '0002_equipospartidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipospartidos',
            name='eq10',
            field=models.CharField(default='Equipo', max_length=100),
        ),
        migrations.AddField(
            model_name='equipospartidos',
            name='eq11',
            field=models.CharField(default='Equipo', max_length=100),
        ),
        migrations.AddField(
            model_name='equipospartidos',
            name='eq12',
            field=models.CharField(default='Equipo', max_length=100),
        ),
        migrations.AddField(
            model_name='equipospartidos',
            name='eq13',
            field=models.CharField(default='Equipo', max_length=100),
        ),
        migrations.AddField(
            model_name='equipospartidos',
            name='eq14',
            field=models.CharField(default='Equipo', max_length=100),
        ),
        migrations.AddField(
            model_name='equipospartidos',
            name='eq15',
            field=models.CharField(default='Equipo', max_length=100),
        ),
        migrations.AddField(
            model_name='equipospartidos',
            name='eq16',
            field=models.CharField(default='Equipo', max_length=100),
        ),
        migrations.AddField(
            model_name='equipospartidos',
            name='eq17',
            field=models.CharField(default='Equipo', max_length=100),
        ),
        migrations.AddField(
            model_name='equipospartidos',
            name='eq18',
            field=models.CharField(default='Equipo', max_length=100),
        ),
        migrations.AddField(
            model_name='equipospartidos',
            name='eq19',
            field=models.CharField(default='Equipo', max_length=100),
        ),
        migrations.AddField(
            model_name='equipospartidos',
            name='eq20',
            field=models.CharField(default='Equipo', max_length=100),
        ),
        migrations.AddField(
            model_name='equipospartidos',
            name='eq21',
            field=models.CharField(default='Equipo', max_length=100),
        ),
        migrations.AddField(
            model_name='equipospartidos',
            name='eq22',
            field=models.CharField(default='Equipo', max_length=100),
        ),
        migrations.AddField(
            model_name='equipospartidos',
            name='eq3',
            field=models.CharField(default='Equipo', max_length=100),
        ),
        migrations.AddField(
            model_name='equipospartidos',
            name='eq4',
            field=models.CharField(default='Equipo', max_length=100),
        ),
        migrations.AddField(
            model_name='equipospartidos',
            name='eq5',
            field=models.CharField(default='Equipo', max_length=100),
        ),
        migrations.AddField(
            model_name='equipospartidos',
            name='eq6',
            field=models.CharField(default='Equipo', max_length=100),
        ),
        migrations.AddField(
            model_name='equipospartidos',
            name='eq7',
            field=models.CharField(default='Equipo', max_length=100),
        ),
        migrations.AddField(
            model_name='equipospartidos',
            name='eq8',
            field=models.CharField(default='Equipo', max_length=100),
        ),
        migrations.AddField(
            model_name='equipospartidos',
            name='eq9',
            field=models.CharField(default='Equipo', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipospartidos',
            name='eq1',
            field=models.CharField(default='Equipo', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipospartidos',
            name='eq2',
            field=models.CharField(default='Equipo', max_length=100),
        ),
    ]
