# Generated by Django 3.2.10 on 2024-01-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llenar_quiniela', '0004_prediccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prediccion',
            name='prediccion',
        ),
        migrations.AddField(
            model_name='prediccion',
            name='pJ1',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=255),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='pJ10',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=255),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='pJ11',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=255),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='pJ12',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=255),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='pJ13',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=255),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='pJ14',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=255),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='pJ15',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=255),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='pJ16',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=255),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='pJ17',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=255),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='pJ2',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=255),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='pJ3',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=255),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='pJ4',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=255),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='pJ5',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=255),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='pJ6',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=255),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='pJ7',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=255),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='pJ8',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=255),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='pJ9',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=255),
        ),
    ]
