# Generated by Django 3.2.10 on 2024-02-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llenar_quiniela', '0005_auto_20240131_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos_quiniela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j1', models.ImageField(blank=True, null=True, upload_to='')),
                ('j2', models.ImageField(blank=True, null=True, upload_to='')),
                ('j3', models.ImageField(blank=True, null=True, upload_to='')),
                ('j4', models.ImageField(blank=True, null=True, upload_to='')),
                ('j5', models.ImageField(blank=True, null=True, upload_to='')),
                ('j6', models.ImageField(blank=True, null=True, upload_to='')),
                ('j7', models.ImageField(blank=True, null=True, upload_to='')),
                ('j8', models.ImageField(blank=True, null=True, upload_to='')),
                ('j9', models.ImageField(blank=True, null=True, upload_to='')),
                ('j10', models.ImageField(blank=True, null=True, upload_to='')),
                ('j11', models.ImageField(blank=True, null=True, upload_to='')),
                ('j12', models.ImageField(blank=True, null=True, upload_to='')),
                ('j13', models.ImageField(blank=True, null=True, upload_to='')),
                ('j14', models.ImageField(blank=True, null=True, upload_to='')),
                ('j15', models.ImageField(blank=True, null=True, upload_to='')),
                ('j16', models.ImageField(blank=True, null=True, upload_to='')),
                ('j17', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
