# Generated by Django 3.2.10 on 2024-02-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llenar_quiniela', '0006_fotos_quiniela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j1',
            field=models.ImageField(blank=True, null=True, upload_to='quiniela'),
        ),
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j10',
            field=models.ImageField(blank=True, null=True, upload_to='quiniela'),
        ),
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j11',
            field=models.ImageField(blank=True, null=True, upload_to='quiniela'),
        ),
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j12',
            field=models.ImageField(blank=True, null=True, upload_to='quiniela'),
        ),
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j13',
            field=models.ImageField(blank=True, null=True, upload_to='quiniela'),
        ),
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j14',
            field=models.ImageField(blank=True, null=True, upload_to='quiniela'),
        ),
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j15',
            field=models.ImageField(blank=True, null=True, upload_to='quiniela'),
        ),
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j16',
            field=models.ImageField(blank=True, null=True, upload_to='quiniela'),
        ),
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j17',
            field=models.ImageField(blank=True, null=True, upload_to='quiniela'),
        ),
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j2',
            field=models.ImageField(blank=True, null=True, upload_to='quiniela'),
        ),
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j3',
            field=models.ImageField(blank=True, null=True, upload_to='quiniela'),
        ),
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j4',
            field=models.ImageField(blank=True, null=True, upload_to='quiniela'),
        ),
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j5',
            field=models.ImageField(blank=True, null=True, upload_to='quiniela'),
        ),
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j6',
            field=models.ImageField(blank=True, null=True, upload_to='quiniela'),
        ),
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j7',
            field=models.ImageField(blank=True, null=True, upload_to='quiniela'),
        ),
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j8',
            field=models.ImageField(blank=True, null=True, upload_to='quiniela'),
        ),
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j9',
            field=models.ImageField(blank=True, null=True, upload_to='quiniela'),
        ),
    ]
