# Generated by Django 3.2.10 on 2024-02-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llenar_quiniela', '0008_auto_20240215_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j1',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j10',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j11',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j12',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j13',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j14',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j15',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j16',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j17',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j2',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j3',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j4',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j5',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j6',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j7',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j8',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='fotos_quiniela',
            name='j9',
            field=models.TextField(default='NC', max_length=1000000),
        ),
    ]
