# Generated by Django 3.2.10 on 2024-02-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llenar_quiniela', '0009_auto_20240220_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagenes_cartas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M', models.TextField(default='NC', max_length=1000000)),
                ('DQ', models.TextField(default='NC', max_length=1000000)),
                ('OD', models.TextField(default='NC', max_length=1000000)),
                ('OT', models.TextField(default='NC', max_length=1000000)),
                ('MA', models.TextField(default='NC', max_length=1000000)),
                ('IQ', models.TextField(default='NC', max_length=1000000)),
                ('J', models.TextField(default='NC', max_length=1000000)),
                ('NC', models.TextField(default='NC', max_length=1000000)),
                ('RC', models.TextField(default='NC', max_length=1000000)),
            ],
        ),
    ]
