# Generated by Django 3.2.10 on 2024-05-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llenar_quiniela', '0012_juegos_pendientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenes_cartas',
            name='T',
            field=models.TextField(default='NC', max_length=1000000),
        ),
    ]
