# Generated by Django 3.2.10 on 2024-05-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llenar_quiniela', '0013_imagenes_cartas_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos_tiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('atlas', models.CharField(default='1', max_length=1)),
                ('america', models.CharField(default='1', max_length=1)),
                ('chivas', models.CharField(default='1', max_length=1)),
                ('cruz_azul', models.CharField(default='1', max_length=1)),
                ('tijuana', models.CharField(default='1', max_length=1)),
                ('puebla', models.CharField(default='1', max_length=1)),
                ('queretaro', models.CharField(default='1', max_length=1)),
                ('pumas', models.CharField(default='1', max_length=1)),
                ('toluca', models.CharField(default='1', max_length=1)),
                ('santos', models.CharField(default='1', max_length=1)),
                ('monterrey', models.CharField(default='1', max_length=1)),
                ('tigres', models.CharField(default='1', max_length=1)),
                ('mazatlan', models.CharField(default='1', max_length=1)),
                ('necaxa', models.CharField(default='1', max_length=1)),
                ('san_luis', models.CharField(default='1', max_length=1)),
                ('leon', models.CharField(default='1', max_length=1)),
                ('juarez', models.CharField(default='1', max_length=1)),
                ('pachuca', models.CharField(default='1', max_length=1)),
            ],
        ),
    ]
