# Generated by Django 3.2.10 on 2024-01-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabla_general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornadas',
            name='suma_j',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
