# Generated by Django 3.2.10 on 2024-02-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabla_general', '0003_equipos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='j1',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=1000),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='j10',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=1000),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='j11',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=1000),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='j12',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=1000),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='j13',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=1000),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='j14',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=1000),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='j15',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=1000),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='j16',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=1000),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='j17',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=1000),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='j2',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=1000),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='j3',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=1000),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='j4',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=1000),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='j5',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=1000),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='j6',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=1000),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='j7',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=1000),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='j8',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=1000),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='j9',
            field=models.CharField(default='X, X, X, X, X, X, X, X, X, X, X', max_length=1000),
        ),
    ]
