# Generated by Django 3.2.10 on 2024-02-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabla_general', '0004_auto_20240202_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='eq',
            field=models.CharField(default='EQUIPOS', max_length=1000),
        ),
    ]
