# Generated by Django 3.2.10 on 2024-02-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabla_general', '0007_puntos_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('j1', models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=50)),
                ('j2', models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=50)),
                ('j3', models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=50)),
                ('j4', models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=50)),
                ('j5', models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=50)),
                ('j6', models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=50)),
                ('j7', models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=50)),
                ('j8', models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=50)),
                ('j9', models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=50)),
                ('j10', models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=50)),
                ('j11', models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=50)),
                ('j12', models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=50)),
                ('j13', models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=50)),
                ('j14', models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=50)),
                ('j15', models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=50)),
                ('j16', models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=50)),
                ('j17', models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=50)),
            ],
        ),
    ]
