# Generated by Django 3.2.10 on 2024-02-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabla_general', '0008_colores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colores',
            name='j1',
            field=models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=500),
        ),
        migrations.AlterField(
            model_name='colores',
            name='j10',
            field=models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=500),
        ),
        migrations.AlterField(
            model_name='colores',
            name='j11',
            field=models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=500),
        ),
        migrations.AlterField(
            model_name='colores',
            name='j12',
            field=models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=500),
        ),
        migrations.AlterField(
            model_name='colores',
            name='j13',
            field=models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=500),
        ),
        migrations.AlterField(
            model_name='colores',
            name='j14',
            field=models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=500),
        ),
        migrations.AlterField(
            model_name='colores',
            name='j15',
            field=models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=500),
        ),
        migrations.AlterField(
            model_name='colores',
            name='j16',
            field=models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=500),
        ),
        migrations.AlterField(
            model_name='colores',
            name='j17',
            field=models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=500),
        ),
        migrations.AlterField(
            model_name='colores',
            name='j2',
            field=models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=500),
        ),
        migrations.AlterField(
            model_name='colores',
            name='j3',
            field=models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=500),
        ),
        migrations.AlterField(
            model_name='colores',
            name='j4',
            field=models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=500),
        ),
        migrations.AlterField(
            model_name='colores',
            name='j5',
            field=models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=500),
        ),
        migrations.AlterField(
            model_name='colores',
            name='j6',
            field=models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=500),
        ),
        migrations.AlterField(
            model_name='colores',
            name='j7',
            field=models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=500),
        ),
        migrations.AlterField(
            model_name='colores',
            name='j8',
            field=models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=500),
        ),
        migrations.AlterField(
            model_name='colores',
            name='j9',
            field=models.CharField(default='lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon, lightsalmon', max_length=500),
        ),
    ]
