# Generated by Django 3.2.10 on 2024-02-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabla_general', '0009_auto_20240203_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartas_aux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('j1', models.CharField(default='NA', max_length=10)),
                ('j2', models.CharField(default='NA', max_length=10)),
                ('j3', models.CharField(default='NA', max_length=10)),
                ('j4', models.CharField(default='NA', max_length=10)),
                ('j5', models.CharField(default='NA', max_length=10)),
                ('j6', models.CharField(default='NA', max_length=10)),
                ('j7', models.CharField(default='NA', max_length=10)),
                ('j8', models.CharField(default='NA', max_length=10)),
                ('j9', models.CharField(default='NA', max_length=10)),
                ('j10', models.CharField(default='NA', max_length=10)),
                ('j11', models.CharField(default='NA', max_length=10)),
                ('j12', models.CharField(default='NA', max_length=10)),
                ('j13', models.CharField(default='NA', max_length=10)),
                ('j14', models.CharField(default='NA', max_length=10)),
                ('j15', models.CharField(default='NA', max_length=10)),
                ('j16', models.CharField(default='NA', max_length=10)),
                ('j17', models.CharField(default='NA', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='jugadores_gol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jug', models.CharField(default='NA', max_length=1000)),
            ],
        ),
    ]
