# Generated by Django 3.2.10 on 2024-02-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabla_general', '0010_cartas_aux_jugadores_gol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugadores_gol',
            old_name='jug',
            new_name='j1',
        ),
        migrations.AddField(
            model_name='jugadores_gol',
            name='j10',
            field=models.CharField(default='NA', max_length=1000),
        ),
        migrations.AddField(
            model_name='jugadores_gol',
            name='j11',
            field=models.CharField(default='NA', max_length=1000),
        ),
        migrations.AddField(
            model_name='jugadores_gol',
            name='j12',
            field=models.CharField(default='NA', max_length=1000),
        ),
        migrations.AddField(
            model_name='jugadores_gol',
            name='j13',
            field=models.CharField(default='NA', max_length=1000),
        ),
        migrations.AddField(
            model_name='jugadores_gol',
            name='j14',
            field=models.CharField(default='NA', max_length=1000),
        ),
        migrations.AddField(
            model_name='jugadores_gol',
            name='j15',
            field=models.CharField(default='NA', max_length=1000),
        ),
        migrations.AddField(
            model_name='jugadores_gol',
            name='j16',
            field=models.CharField(default='NA', max_length=1000),
        ),
        migrations.AddField(
            model_name='jugadores_gol',
            name='j17',
            field=models.CharField(default='NA', max_length=1000),
        ),
        migrations.AddField(
            model_name='jugadores_gol',
            name='j2',
            field=models.CharField(default='NA', max_length=1000),
        ),
        migrations.AddField(
            model_name='jugadores_gol',
            name='j3',
            field=models.CharField(default='NA', max_length=1000),
        ),
        migrations.AddField(
            model_name='jugadores_gol',
            name='j4',
            field=models.CharField(default='NA', max_length=1000),
        ),
        migrations.AddField(
            model_name='jugadores_gol',
            name='j5',
            field=models.CharField(default='NA', max_length=1000),
        ),
        migrations.AddField(
            model_name='jugadores_gol',
            name='j6',
            field=models.CharField(default='NA', max_length=1000),
        ),
        migrations.AddField(
            model_name='jugadores_gol',
            name='j7',
            field=models.CharField(default='NA', max_length=1000),
        ),
        migrations.AddField(
            model_name='jugadores_gol',
            name='j8',
            field=models.CharField(default='NA', max_length=1000),
        ),
        migrations.AddField(
            model_name='jugadores_gol',
            name='j9',
            field=models.CharField(default='NA', max_length=1000),
        ),
    ]
