# Generated by Django 3.2.10 on 2024-02-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabla_general', '0011_auto_20240209_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Num_quiniela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_jor', models.CharField(max_length=10)),
            ],
        ),
    ]
