# Generated by Django 3.2.10 on 2024-02-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabla_general', '0013_puntos_cartas'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornadas',
            name='suma_j_c',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
