# Generated by Django 3.2.10 on 2024-05-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos_portada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podium', models.TextField(default='NC', max_length=1000000)),
                ('historico', models.TextField(default='NC', max_length=1000000)),
                ('descenso', models.TextField(default='NC', max_length=1000000)),
            ],
        ),
    ]
